### ISSUE TITLE
Requests timing out with empty response 

### ISSUE THREAD

**Issue by boltgolt** [costastf/toonlib#2]
Every request after the very first one is timing out with a 200 status but no body. 

Running the following code reproduces the issue:

```python
from toonlib import Toon
import time

eneco_username = 'xxxx'
eneco_password = 'xxxx'
toon = Toon(eneco_username, eneco_password)

while True:
    time.sleep(5)
    print(toon.power)
```

I'm guessing this is because of a session failure, if i set a client-side timeout and force a new login the issue disappears. That means the solution seems to be to relog after every every request, but i'm not sure eneco will be happy with that clearly non-native traffic volume.

**Comment by costastf** [comment]
After a little bit of digging around it seems that they have implemented Oauth and there are tokens and refresh tokens and such. So we definitely should not reauthenticate every time but we should try to implement the proper authentication method. I will keep looking into it...

**Comment by boltgolt** [comment]
I wasn't very happy with the reauth fix either, but it did solve every issue I had. I agree though, this should be a last resort if nothing else works. 

What I noticed on my (probably less extensive) testing is that every request that took longer than a second or two would timeout. The Toon app would also be very unresponsive at this time, which is why I originally thought it was an rate limit issue. 

Now Toon is opening up and everyone is allowed to use the API, could it be helpful to contact them directly?

**Comment by costastf** [comment]
Could you share a bit more about toon opening up? Where did you get that from?

**Comment by boltgolt** [comment]
I found it in the community thread: https://community.home-assistant.io/t/toon-van-eneco-custom-component/16027/89

**Comment by costastf** [comment]
Sadly that is not new and it does not work for us. This is open for sanctioned apps that go through toon's acceptance process and I don't think it could cover a usage like toonlib.

**Comment by boltgolt** [comment]
Ah that's a shame. Either way the register page throws a 500 error so i'm not that impressed.

At the very least toonlib should have a timeout of less than 10 seconds in the request i modified, i'll continue to monitor the traffic to see other anomalies.

**Comment by boltgolt** [comment]
Did more testing today and tried out [this](https://community.home-assistant.io/t/toon-van-eneco-custom-component/16027/104) form post.

At first both toonlib and the Toon app reported a constant power usage of 244 watt, even though the Toon unit itself was reporting completely different values. Changing the program on the unit did not change it in app either.

Then i did what helped the other guy: Logged out of the Toon app and then logged back in. The power value updated immediately on both the app and in toonlib and continues to update.

It really seems as we need to relog once in a while, but the effects say quite long. It has been at least 2 hours since i did a relog and it's still working fine

**Comment by costastf** [comment]
This probably means that their api gets stuck. This means that there is not much we can do on the library side and re authenticating would only make things worst for their system I think.

**Comment by costastf** [comment]
@Boltgolt what I suggest is for you to make the change locally and have it running for a while. If the re authentication unblocks the api and is not aggressive it might be better than constantly querying and getting a time out. We just need to make sure that we do not spam their servers so if you could make some benchmarking in your local instance and get back with positive feedback, like we need to re-authenticate once every three days for example and that makes the problem goes away then we will implement it in the library. I just don't want to be in a situation where we re-authenticate in every timeout and that still times out and we have everybody using this component re-authenticating and timing out all the time. Makes sense?

**Comment by costastf** [comment]
I have created a timeout_workaround branch with the changes. If you could give it a try and report back your findings here it would be great. If they are very positive, where a re authentication happens rarely and unblocks everything I will change the exception handling to recursion so it is safer and does not crash.

**Comment by boltgolt** [comment]
I've pulled the branch and modified it to write to a csv file, so we should be getting a nice enormous  spreadsheet of data. I'll run it as much as possible the coming days.

**Comment by costastf** [comment]
That is awesome! When you have some meaningful metrics of the rate of occurrence please post them here so we can take the appropriate action. Thanks for this!

**Comment by remkolodder** [comment]
Hi,

I have similiar issues. I ditch the data to influxdb and then graph them via Grafana. I noticed that it works for around 2 hours and then the information gets lost.

I am trying the patch from boltgolt to see whether that works in getting around the issue :-)

**Comment by costastf** [comment]
Please refrain from using the patch until we have more data on how it
behaves. As soon as there is a clear picture on what the side effects are
it will be implemented in the component.

**Comment by remkolodder** [comment]
for what it's worth; it didn't change the current situation (for me). I have reverted to the original lib files.

**Comment by boltgolt** [comment]
I've got some first results, but they don't look very promising. The full sheet is available [here](https://docs.google.com/spreadsheets/d/1aGuHjzJZY8fApqw7-36mdiLvyvbmDmzAk-8MWDq9luo/edit), but in short: While there seem to be long periods of stability, the avarage time between forced relogs is a little more than 2 and a half hours. The incredibly unhelpful graph shows that the all relogs happen in the evening, but we need more data to verify that. 

On a positive note: Every time a relog was needed it did fix the problem, no crashes have occurred.

**Comment by remkolodder** [comment]
Perhaps the mijnpon module can be of a little help. The VW stuff does more or less the same as Toon does, wrt. oauth I believe.

https://github.com/bramkragten/python-mijnpon

**Comment by costastf** [comment]
Hi @remkolodder, I don't see usage of oauth for the api and the inconsistency of the failures according to @Boltgolt 's measurements indicate an environmental reason and not a systemic one. Thanks for looking  into it though :)

**Comment by costastf** [comment]
https://github.com/costastf/toonlib/pull/4 closes this.
